# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-19 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zerver', '0093_subscription_event_log_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmessage',
            name='triggers_slash_command',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='triggers_slash_command',
            field=models.BooleanField(default=False),
        ),
    ]
